default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "feanor") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  pool: 5

development:
  <<: *default
  database: island_development

test:
  <<: *default
  database: island_test
production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: island_production
    username: deploy
    password: <%= ENV["ISLAND_DATABASE_PASSWORD"] %>
    host: localhost
    pool: 5

  cable:
    adapter: postgresql
    encoding: unicode
    database: island_cable_production
    username: deploy
    password: <%= ENV["ISLAND_DATABASE_PASSWORD"] %>
    host: localhost
    pool: 5

  queue:
    adapter: postgresql
    encoding: unicode
    database: island_queue_production
    username: deploy
    password: <%= ENV["ISLAND_DATABASE_PASSWORD"] %>
    host: localhost
    pool: 5

  cache:
    adapter: postgresql
    encoding: unicode
    database: island_cache_production
    username: deploy
    password: <%= ENV["ISLAND_DATABASE_PASSWORD"] %>
    host: localhost
    pool: 5
