default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "feanor") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  pool: 5

development:
  <<: *default
  database: island_development

test:
  <<: *default
  database: island_test

production:
  adapter: postgresql
  encoding: unicode
  database: island_production
  username: island
  password: <%= ENV['ISLAND_DATABASE_PASSWORD'] %>
  host: 127.0.0.1

